/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computervision.chapter3.ex28;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author hsmilton
 */
public class Exercise28JFrame extends javax.swing.JFrame {

    private int kernelSize = 5;
    private int diameter = 15;
    private int sigmaColor = 80;
    private int sigmaSpace = 80;

    private JLabel j2;

    /**
     * Creates new form Exercise28JFrame
     */
    public Exercise28JFrame() {
        initComponents();

        JLabel j = new JLabel(new ImageIcon(Exercise28.mat2BufferedImage(Exercise28.read("lena.png"))));
        jPanelOriginal.add(j);

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOriginal = new javax.swing.JPanel();
        jPanelMedianBlur = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabelKernel = new javax.swing.JLabel();
        jLabelMedianBlur = new JLabel(new ImageIcon(Exercise28.blur("lena.png", kernelSize)));
        jPanelBilateralFilter = new javax.swing.JPanel();
        jSlider2 = new javax.swing.JSlider();
        jLabelDiameter = new javax.swing.JLabel();
        jLabelBilateralFilter = new JLabel(new ImageIcon(Exercise28.bilateralFilterCV("lena.png", diameter, sigmaColor, sigmaSpace)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        jPanelOriginal.setBorder(javax.swing.BorderFactory.createTitledBorder("Original image"));
        jPanelOriginal.setLayout(new javax.swing.BoxLayout(jPanelOriginal, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(jPanelOriginal);

        jPanelMedianBlur.setBorder(javax.swing.BorderFactory.createTitledBorder("Median blur"));
        jPanelMedianBlur.setLayout(new javax.swing.BoxLayout(jPanelMedianBlur, javax.swing.BoxLayout.Y_AXIS));

        jSlider1.setMaximum(55);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(1);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanelMedianBlur.add(jSlider1);

        jLabelKernel.setText("kernel:");
        jPanelMedianBlur.add(jLabelKernel);
        jPanelMedianBlur.add(jLabelMedianBlur);

        getContentPane().add(jPanelMedianBlur);

        jPanelBilateralFilter.setBorder(javax.swing.BorderFactory.createTitledBorder("Bilateral filter"));
        jPanelBilateralFilter.setLayout(new javax.swing.BoxLayout(jPanelBilateralFilter, javax.swing.BoxLayout.Y_AXIS));

        jSlider2.setMaximum(55);
        jSlider2.setMinimum(1);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(1);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jPanelBilateralFilter.add(jSlider2);

        jLabelDiameter.setText("diameter: ");
        jPanelBilateralFilter.add(jLabelDiameter);
        jPanelBilateralFilter.add(jLabelBilateralFilter);

        getContentPane().add(jPanelBilateralFilter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        kernelSize = jSlider1.getValue();

        kernelSize = kernelSize % 2 == 0 ? kernelSize + 1 : kernelSize;

        System.out.println("kernel size---> " + kernelSize);
        jLabelKernel.setText("Kernel: " + kernelSize);

        jLabelMedianBlur.setIcon(new ImageIcon(Exercise28.blur("lena.png", kernelSize)));

        repaint();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        diameter = jSlider2.getValue();

        System.out.println("diameter size---> " + diameter);
        jLabelDiameter.setText("Diameter: " + kernelSize);

        jLabelBilateralFilter.setIcon(new ImageIcon(Exercise28.bilateralFilterCV("lena.png", diameter, sigmaColor, sigmaSpace)));

        repaint();
    }//GEN-LAST:event_jSlider2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercise28JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercise28JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercise28JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercise28JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercise28JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBilateralFilter;
    private javax.swing.JLabel jLabelDiameter;
    private javax.swing.JLabel jLabelKernel;
    private javax.swing.JLabel jLabelMedianBlur;
    private javax.swing.JPanel jPanelBilateralFilter;
    private javax.swing.JPanel jPanelMedianBlur;
    private javax.swing.JPanel jPanelOriginal;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    // End of variables declaration//GEN-END:variables
}
