package computervision.chapter2.ex26;

import javax.swing.JLabel;

/**
 *
 * @author hamilton.matos
 */
public class ImageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImageJPanel
     */
    public ImageJPanel() {
        initComponents();

    }

    public ImageJPanel(JLabel iconImage) {
        initComponents();                          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelB1 = new javax.swing.JLabel();
        jLabelG1 = new javax.swing.JLabel();
        jLabelR1 = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jLabelG = new javax.swing.JLabel();
        jLabelR = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem X"));

        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        jLabelB1.setForeground(new java.awt.Color(51, 102, 255));
        jLabelB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelB1.setText("B");
        jPanel1.add(jLabelB1);

        jLabelG1.setForeground(new java.awt.Color(0, 153, 0));
        jLabelG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelG1.setText("G");
        jPanel1.add(jLabelG1);

        jLabelR1.setForeground(new java.awt.Color(204, 0, 0));
        jLabelR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelR1.setText("R");
        jPanel1.add(jLabelR1);

        jLabelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelB.setText("jLabel1");
        jPanel1.add(jLabelB);

        jLabelG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelG.setText("jLabel1");
        jPanel1.add(jLabelG);

        jLabelR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelR.setText("jLabel1");
        jPanel1.add(jLabelR);

        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getjLabelImage() {
        return jLabelImage;
    }

    public void setjLabelImage(JLabel jLabelImage) {
        this.jLabelImage = jLabelImage;
    }

    public JLabel getjLabelB() {
        return jLabelB;
    }

    public void setjLabelB(JLabel jLabelB) {
        this.jLabelB = jLabelB;
    }

    public JLabel getjLabelG() {
        return jLabelG;
    }

    public void setjLabelG(JLabel jLabelG) {
        this.jLabelG = jLabelG;
    }

    public JLabel getjLabelR() {
        return jLabelR;
    }

    public void setjLabelR(JLabel jLabelR) {
        this.jLabelR = jLabelR;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelB1;
    private javax.swing.JLabel jLabelG;
    private javax.swing.JLabel jLabelG1;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelR;
    private javax.swing.JLabel jLabelR1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
