/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computervision.chapter2.ex22;

import java.text.DecimalFormat;
import lombok.Getter;
import lombok.Setter;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//computervision.chapter2.ex22//MainWindow//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "MainWindowTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "computervision.chapter2.ex22.MainWindowTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_MainWindowAction",
        preferredID = "MainWindowTopComponent"
)
@Messages({
    "CTL_MainWindowAction=Exercise 2.2",
    "CTL_MainWindowTopComponent=MainWindow Window",
    "HINT_MainWindowTopComponent=This is a MainWindow window"
})
@Getter
@Setter
public final class MainWindowTopComponent extends TopComponent {

    private int similarityValue = 0;
    private int similarityA;
    private int similarityB;
    private int similarityTX;
    private int similarityTY;
    private int a00;
    private int a01;
    private int a02;
    private int a10;
    private int a11;
    private int a12;
    private int perspA00;
    private int perspA01;
    private int perspA02;
    private int perspA10;
    private int perspA11;
    private int perspA12;
    private int perspA20;
    private int perspA21;
    private int perspA22;

    public MainWindowTopComponent() {
        initComponents();
        setName(Bundle.CTL_MainWindowTopComponent());
        setToolTipText(Bundle.HINT_MainWindowTopComponent());
        
        drawingPane.setMainTopComponent(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawingPane = new computervision.chapter2.ex22.DrawingPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelR00 = new javax.swing.JLabel();
        jLabelR01 = new javax.swing.JLabel();
        jLabelR02 = new javax.swing.JLabel();
        jLabelR03 = new javax.swing.JLabel();
        jLabelR10 = new javax.swing.JLabel();
        jLabelR11 = new javax.swing.JLabel();
        jLabelR12 = new javax.swing.JLabel();
        jLabelR13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelTranslation = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelRigid = new javax.swing.JPanel();
        jSlider4 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jPanelSimilarity = new javax.swing.JPanel();
        jSlider3 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jSliderSimA = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jSliderSimB = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jSliderSimTX = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jSliderSimTY = new javax.swing.JSlider();
        jPanelAffine = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSliderA00 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jSliderA01 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jSliderA02 = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jSliderA10 = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        jSliderA12 = new javax.swing.JSlider();
        jSliderA11 = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        jPanelPerspective = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSliderPerspA00 = new javax.swing.JSlider();
        jLabel15 = new javax.swing.JLabel();
        jSliderPerspA01 = new javax.swing.JSlider();
        jLabel16 = new javax.swing.JLabel();
        jSliderPerspA02 = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        jSliderPerspA10 = new javax.swing.JSlider();
        jLabel18 = new javax.swing.JLabel();
        jSliderPerspA12 = new javax.swing.JSlider();
        jSliderPerspA11 = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSliderPerspA21 = new javax.swing.JSlider();
        jSliderPerspA20 = new javax.swing.JSlider();
        jLabel21 = new javax.swing.JLabel();
        jSliderPerspA22 = new javax.swing.JSlider();
        jLabel22 = new javax.swing.JLabel();

        setDisplayName(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.displayName")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton6, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton7, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton7.text")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton8, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton8.text")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton9, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton9.text")); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton10, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jButton10.text")); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanel2.border.title"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanel4.border.title"))); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(2, 4, 60, 20));

        org.openide.awt.Mnemonics.setLocalizedText(jLabelR00, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabelR00.text")); // NOI18N
        jPanel4.add(jLabelR00);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelR01, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabelR01.text")); // NOI18N
        jPanel4.add(jLabelR01);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelR02, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabelR02.text")); // NOI18N
        jPanel4.add(jLabelR02);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelR03, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabelR03.text")); // NOI18N
        jPanel4.add(jLabelR03);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelR10, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabelR10.text")); // NOI18N
        jPanel4.add(jLabelR10);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelR11, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabelR11.text")); // NOI18N
        jPanel4.add(jLabelR11);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelR12, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabelR12.text")); // NOI18N
        jPanel4.add(jLabelR12);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelR13, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabelR13.text")); // NOI18N
        jPanel4.add(jLabelR13);

        jSlider1.setMaximum(200);
        jSlider1.setMinimum(-200);
        jSlider1.setValue(1);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });

        jSlider2.setMaximum(200);
        jSlider2.setMinimum(-200);
        jSlider2.setValue(1);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jSlider2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider2MouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel1.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout jPanelTranslationLayout = new javax.swing.GroupLayout(jPanelTranslation);
        jPanelTranslation.setLayout(jPanelTranslationLayout);
        jPanelTranslationLayout.setHorizontalGroup(
            jPanelTranslationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTranslationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTranslationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTranslationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTranslationLayout.setVerticalGroup(
            jPanelTranslationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTranslationLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTranslationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTranslationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(362, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanelTranslation.TabConstraints.tabTitle"), jPanelTranslation); // NOI18N

        jSlider4.setMaximum(200);
        jSlider4.setMinimum(-200);
        jSlider4.setValue(1);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });
        jSlider4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider4MouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout jPanelRigidLayout = new javax.swing.GroupLayout(jPanelRigid);
        jPanelRigid.setLayout(jPanelRigidLayout);
        jPanelRigidLayout.setHorizontalGroup(
            jPanelRigidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRigidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRigidLayout.setVerticalGroup(
            jPanelRigidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRigidLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelRigidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(396, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanelRigid.TabConstraints.tabTitle"), jPanelRigid); // NOI18N

        jPanelSimilarity.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanelSimilarity.border.title"))); // NOI18N

        jSlider3.setMaximum(200);
        jSlider3.setMinimum(-200);
        jSlider3.setValue(1);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });
        jSlider3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider3MouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel4.text")); // NOI18N

        jSliderSimA.setMaximum(200);
        jSliderSimA.setMinimum(-200);
        jSliderSimA.setValue(1);
        jSliderSimA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSimAStateChanged(evt);
            }
        });
        jSliderSimA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderSimAMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel5.text")); // NOI18N

        jSliderSimB.setMaximum(200);
        jSliderSimB.setMinimum(-200);
        jSliderSimB.setValue(0);
        jSliderSimB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSimBStateChanged(evt);
            }
        });
        jSliderSimB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderSimBMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel6.text")); // NOI18N

        jSliderSimTX.setMaximum(200);
        jSliderSimTX.setMinimum(-200);
        jSliderSimTX.setValue(1);
        jSliderSimTX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSimTXStateChanged(evt);
            }
        });
        jSliderSimTX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderSimTXMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel7.text")); // NOI18N

        jSliderSimTY.setMaximum(200);
        jSliderSimTY.setMinimum(-200);
        jSliderSimTY.setValue(1);
        jSliderSimTY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSimTYStateChanged(evt);
            }
        });
        jSliderSimTY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderSimTYMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelSimilarityLayout = new javax.swing.GroupLayout(jPanelSimilarity);
        jPanelSimilarity.setLayout(jPanelSimilarityLayout);
        jPanelSimilarityLayout.setHorizontalGroup(
            jPanelSimilarityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimilarityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSimilarityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addGroup(jPanelSimilarityLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderSimA, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelSimilarityLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderSimB, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelSimilarityLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderSimTX, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelSimilarityLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderSimTY, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSimilarityLayout.setVerticalGroup(
            jPanelSimilarityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimilarityLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSimilarityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderSimA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSimilarityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderSimB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSimilarityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderSimTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSimilarityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderSimTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanelSimilarity.TabConstraints.tabTitle"), jPanelSimilarity); // NOI18N

        jPanelAffine.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanelAffine.border.title"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel8.text")); // NOI18N

        jSliderA00.setMaximum(200);
        jSliderA00.setMinimum(-200);
        jSliderA00.setValue(1);
        jSliderA00.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderA00StateChanged(evt);
            }
        });
        jSliderA00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderA00MouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel9.text")); // NOI18N

        jSliderA01.setMaximum(200);
        jSliderA01.setMinimum(-200);
        jSliderA01.setValue(0);
        jSliderA01.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderA01StateChanged(evt);
            }
        });
        jSliderA01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderA01MouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel10.text")); // NOI18N

        jSliderA02.setMaximum(200);
        jSliderA02.setMinimum(-200);
        jSliderA02.setValue(1);
        jSliderA02.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderA02StateChanged(evt);
            }
        });
        jSliderA02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderA02MouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel11.text")); // NOI18N

        jSliderA10.setMaximum(200);
        jSliderA10.setMinimum(-200);
        jSliderA10.setValue(1);
        jSliderA10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderA10StateChanged(evt);
            }
        });
        jSliderA10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderA10MouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel12.text")); // NOI18N

        jSliderA12.setMaximum(200);
        jSliderA12.setMinimum(-200);
        jSliderA12.setValue(1);
        jSliderA12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderA12StateChanged(evt);
            }
        });
        jSliderA12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderA12MouseReleased(evt);
            }
        });

        jSliderA11.setMaximum(200);
        jSliderA11.setMinimum(-200);
        jSliderA11.setValue(1);
        jSliderA11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderA11StateChanged(evt);
            }
        });
        jSliderA11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderA11MouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel13.text")); // NOI18N

        javax.swing.GroupLayout jPanelAffineLayout = new javax.swing.GroupLayout(jPanelAffine);
        jPanelAffine.setLayout(jPanelAffineLayout);
        jPanelAffineLayout.setHorizontalGroup(
            jPanelAffineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAffineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAffineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAffineLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderA00, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelAffineLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderA01, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelAffineLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderA02, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelAffineLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderA10, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelAffineLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderA11, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelAffineLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderA12, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAffineLayout.setVerticalGroup(
            jPanelAffineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAffineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAffineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderA00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAffineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderA01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAffineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderA02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAffineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderA10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAffineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderA11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAffineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderA12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanelAffine.TabConstraints.tabTitle"), jPanelAffine); // NOI18N

        jPanelPerspective.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanelPerspective.border.title"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel14.text")); // NOI18N

        jSliderPerspA00.setMaximum(200);
        jSliderPerspA00.setMinimum(-200);
        jSliderPerspA00.setValue(1);
        jSliderPerspA00.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPerspA00StateChanged(evt);
            }
        });
        jSliderPerspA00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPerspA00MouseReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel15.text")); // NOI18N

        jSliderPerspA01.setMaximum(200);
        jSliderPerspA01.setMinimum(-200);
        jSliderPerspA01.setValue(0);
        jSliderPerspA01.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPerspA01StateChanged(evt);
            }
        });
        jSliderPerspA01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPerspA01MouseReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel16, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel16.text")); // NOI18N

        jSliderPerspA02.setMaximum(200);
        jSliderPerspA02.setMinimum(-200);
        jSliderPerspA02.setValue(1);
        jSliderPerspA02.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPerspA02StateChanged(evt);
            }
        });
        jSliderPerspA02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPerspA02MouseReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel17, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel17.text")); // NOI18N

        jSliderPerspA10.setMaximum(200);
        jSliderPerspA10.setMinimum(-200);
        jSliderPerspA10.setValue(1);
        jSliderPerspA10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPerspA10StateChanged(evt);
            }
        });
        jSliderPerspA10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPerspA10MouseReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel18, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel18.text")); // NOI18N

        jSliderPerspA12.setMaximum(200);
        jSliderPerspA12.setMinimum(-200);
        jSliderPerspA12.setValue(1);
        jSliderPerspA12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPerspA12StateChanged(evt);
            }
        });
        jSliderPerspA12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPerspA12MouseReleased(evt);
            }
        });

        jSliderPerspA11.setMaximum(200);
        jSliderPerspA11.setMinimum(-200);
        jSliderPerspA11.setValue(1);
        jSliderPerspA11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPerspA11StateChanged(evt);
            }
        });
        jSliderPerspA11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPerspA11MouseReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel19, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel19.text")); // NOI18N

        jLabel20.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel20, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel20.text")); // NOI18N

        jSliderPerspA21.setMaximum(200);
        jSliderPerspA21.setMinimum(-200);
        jSliderPerspA21.setValue(1);
        jSliderPerspA21.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPerspA21StateChanged(evt);
            }
        });
        jSliderPerspA21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPerspA21MouseReleased(evt);
            }
        });

        jSliderPerspA20.setMaximum(200);
        jSliderPerspA20.setMinimum(-200);
        jSliderPerspA20.setValue(1);
        jSliderPerspA20.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPerspA20StateChanged(evt);
            }
        });
        jSliderPerspA20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPerspA20MouseReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel21, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel21.text")); // NOI18N

        jSliderPerspA22.setMaximum(200);
        jSliderPerspA22.setMinimum(-200);
        jSliderPerspA22.setValue(1);
        jSliderPerspA22.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPerspA22StateChanged(evt);
            }
        });
        jSliderPerspA22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderPerspA22MouseReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel22, org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jLabel22.text")); // NOI18N

        javax.swing.GroupLayout jPanelPerspectiveLayout = new javax.swing.GroupLayout(jPanelPerspective);
        jPanelPerspective.setLayout(jPanelPerspectiveLayout);
        jPanelPerspectiveLayout.setHorizontalGroup(
            jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPerspA00, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPerspA01, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPerspA02, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPerspA10, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPerspA11, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPerspA12, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPerspA20, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPerspA21, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderPerspA22, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPerspectiveLayout.setVerticalGroup(
            jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerspectiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderPerspA00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderPerspA01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderPerspA02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderPerspA10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderPerspA11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderPerspA12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderPerspA20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderPerspA21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPerspectiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderPerspA22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(MainWindowTopComponent.class, "MainWindowTopComponent.jPanelPerspective.TabConstraints.tabTitle"), jPanelPerspective); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(drawingPane, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addGap(579, 579, 579))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 420, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drawingPane, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        drawingPane.shearXPlus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        drawingPane.shearXMinus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        drawingPane.shearYPlus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        drawingPane.shearYMinus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        drawingPane.reset();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        double ang = 0.5;
        drawingPane.rotateClockwise(0.2);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        drawingPane.reflectionX();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        drawingPane.reflectionY();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        drawingPane.scaleUp();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        drawingPane.scaleDown();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        int value = jSlider1.getValue();
        double v = value / 10;

        drawingPane.setMatrix02(v);
        drawingPane.recalculatePosition();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
        jSlider1.setValue(0);
    }//GEN-LAST:event_jSlider1MouseReleased

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        int value = jSlider2.getValue();
        double v = value / 10;

        drawingPane.setMatrix12(v);
        drawingPane.recalculatePosition();
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MouseReleased
        jSlider2.setValue(0);
    }//GEN-LAST:event_jSlider2MouseReleased

    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
        drawingPane.euclidean();
    }//GEN-LAST:event_jSlider4StateChanged

    private void jSlider4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider4MouseReleased

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged

        if (jSlider3.getValue() > similarityValue) {
            drawingPane.similarityUp();
        } else {
            //decrease
        }

        similarityValue = jSlider3.getValue();
        //        int value = jSlider3.getValue();
        //
        //        if (value > 0) {
            //            drawingPane.scaleUp();
            //        } else {
            //            drawingPane.scaleDown();
            //        }
    }//GEN-LAST:event_jSlider3StateChanged

    private void jSlider3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider3MouseReleased
        //jSlider3.setValue(1);
    }//GEN-LAST:event_jSlider3MouseReleased

    private void jSliderSimAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSimAStateChanged
        if (jSliderSimA.getValue() > similarityA) {
            drawingPane.similarityUp(
                1.05,
                0,
                1,
                1);
        } else {
            drawingPane.similarityUp(
                -1.05,
                0,
                1,
                1);
        }

        similarityA = jSliderSimA.getValue();
    }//GEN-LAST:event_jSliderSimAStateChanged

    private void jSliderSimAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderSimAMouseReleased
        jSliderSimA.setValue(1);
    }//GEN-LAST:event_jSliderSimAMouseReleased

    private void jSliderSimBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSimBStateChanged
        if (jSliderSimB.getValue() > similarityB) {
            drawingPane.similarityUp(
                1,
                0.05,
                1,
                1);
        } else {
            drawingPane.similarityUp(
                1,
                -0.05,
                1,
                1);
        }

        similarityB = jSliderSimB.getValue();
    }//GEN-LAST:event_jSliderSimBStateChanged

    private void jSliderSimBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderSimBMouseReleased
        jSliderSimB.setValue(0);
    }//GEN-LAST:event_jSliderSimBMouseReleased

    private void jSliderSimTXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSimTXStateChanged
        if (jSliderSimTX.getValue() > similarityTX) {
            drawingPane.similarityUp(
                1,
                0,
                1.05,
                1);
        } else {
            drawingPane.similarityUp(
                1,
                0,
                -1.05,
                1);
        }

        similarityTX = jSliderSimTX.getValue();
    }//GEN-LAST:event_jSliderSimTXStateChanged

    private void jSliderSimTXMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderSimTXMouseReleased
        jSliderSimTX.setValue(1);
    }//GEN-LAST:event_jSliderSimTXMouseReleased

    private void jSliderSimTYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSimTYStateChanged
        if (jSliderSimTY.getValue() > similarityTY) {
            drawingPane.similarityUp(
                1,
                0,
                1,
                1.05);
        } else {
            drawingPane.similarityUp(
                1,
                0,
                1,
                -1.05);
        }

        similarityTY = jSliderSimTY.getValue();
    }//GEN-LAST:event_jSliderSimTYStateChanged

    private void jSliderSimTYMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderSimTYMouseReleased
        jSliderSimTY.setValue(1);
    }//GEN-LAST:event_jSliderSimTYMouseReleased

    private void jSliderA00StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderA00StateChanged
        if (jSliderA00.getValue() > a00) {
            drawingPane.affine(
                1.05, 0, 0,
                0, 1, 0
            );
        } else {
            drawingPane.affine(
                -1.05, 0, 0,
                0, 1, 0
            );
        }

        a00 = jSliderA00.getValue();
    }//GEN-LAST:event_jSliderA00StateChanged

    private void jSliderA00MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderA00MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderA00MouseReleased

    private void jSliderA01StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderA01StateChanged
        if (jSliderA01.getValue() > a01) {
            drawingPane.affine(
                1, 0.05, 0,
                0, 1, 0
            );
        } else {
            drawingPane.affine(
                1, -0.05, 0,
                0, 1, 0
            );
        }

        a01 = jSliderA01.getValue();
    }//GEN-LAST:event_jSliderA01StateChanged

    private void jSliderA01MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderA01MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderA01MouseReleased

    private void jSliderA02StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderA02StateChanged
        if (jSliderA02.getValue() > a02) {
            drawingPane.affine(
                1, 0, 0.05,
                0, 1, 0
            );
        } else {
            drawingPane.affine(
                1, 0, -0.05,
                0, 1, 0
            );
        }

        a02 = jSliderA02.getValue();
    }//GEN-LAST:event_jSliderA02StateChanged

    private void jSliderA02MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderA02MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderA02MouseReleased

    private void jSliderA10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderA10StateChanged
        if (jSliderA10.getValue() > a10) {
            drawingPane.affine(
                1, 0, 0,
                0.05, 1, 0
            );
        } else {
            drawingPane.affine(
                1, 0, 0,
                -0.05, 1, 0
            );
        }

        a10 = jSliderA10.getValue();
    }//GEN-LAST:event_jSliderA10StateChanged

    private void jSliderA10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderA10MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderA10MouseReleased

    private void jSliderA12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderA12StateChanged
        if (jSliderA12.getValue() > a12) {
            drawingPane.affine(
                1, 0, 0,
                0, 1.05, 0
            );
        } else {
            drawingPane.affine(
                1, 0, 0,
                0, -1.05, 0
            );
        }

        a12 = jSliderA12.getValue();
    }//GEN-LAST:event_jSliderA12StateChanged

    private void jSliderA12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderA12MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderA12MouseReleased

    private void jSliderA11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderA11StateChanged
        if (jSliderA11.getValue() > a11) {
            drawingPane.affine(
                1, 0, 0,
                0, 1, 0.05
            );
        } else {
            drawingPane.affine(
                1, 0, 0,
                0, 1, -0.05
            );
        }

        a11 = jSliderA11.getValue();
    }//GEN-LAST:event_jSliderA11StateChanged

    private void jSliderA11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderA11MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderA11MouseReleased

    private void jSliderPerspA00StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPerspA00StateChanged
        if (jSliderPerspA00.getValue() > perspA00) {
            drawingPane.affine(
                1.05, 0, 0,
                0, 1, 0
            );
        } else {
            drawingPane.affine(
                -1.05, 0, 0,
                0, 1, 0
            );
        }

        perspA00 = jSliderPerspA00.getValue();
    }//GEN-LAST:event_jSliderPerspA00StateChanged

    private void jSliderPerspA00MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPerspA00MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPerspA00MouseReleased

    private void jSliderPerspA01StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPerspA01StateChanged
        if (jSliderPerspA01.getValue() > perspA01) {
            drawingPane.affine(
                1, 0.05, 0,
                0, 1, 0
            );
        } else {
            drawingPane.affine(
                1, -0.05, 0,
                0, 1, 0
            );
        }

        perspA01 = jSliderPerspA01.getValue();
    }//GEN-LAST:event_jSliderPerspA01StateChanged

    private void jSliderPerspA01MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPerspA01MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPerspA01MouseReleased

    private void jSliderPerspA02StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPerspA02StateChanged
        if (jSliderPerspA02.getValue() > perspA02) {
            drawingPane.affine(
                1, 0, 0.05,
                0, 1, 0
            );
        } else {
            drawingPane.affine(
                1, 0, -0.05,
                0, 1, 0
            );
        }

        perspA02 = jSliderPerspA02.getValue();
    }//GEN-LAST:event_jSliderPerspA02StateChanged

    private void jSliderPerspA02MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPerspA02MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPerspA02MouseReleased

    private void jSliderPerspA10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPerspA10StateChanged
        if (jSliderPerspA10.getValue() > perspA10) {
            drawingPane.affine(
                1, 0, 0,
                0.05, 1, 0
            );
        } else {
            drawingPane.affine(
                1, 0, 0,
                -0.05, 1, 0
            );
        }

        perspA10 = jSliderPerspA10.getValue();
    }//GEN-LAST:event_jSliderPerspA10StateChanged

    private void jSliderPerspA10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPerspA10MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPerspA10MouseReleased

    private void jSliderPerspA12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPerspA12StateChanged
        if (jSliderPerspA12.getValue() > perspA12) {
            drawingPane.affine(
                1, 0, 0,
                0, 1, 0.05
            );
        } else {
            drawingPane.affine(
                1, 0, 0,
                0, 1, -0.05
            );
        }

        perspA12 = jSliderPerspA12.getValue();
    }//GEN-LAST:event_jSliderPerspA12StateChanged

    private void jSliderPerspA12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPerspA12MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPerspA12MouseReleased

    private void jSliderPerspA11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPerspA11StateChanged
        if (jSliderPerspA11.getValue() > perspA11) {
            drawingPane.affine(
                1, 0, 0,
                0, 1.05, 0
            );
        } else {
            drawingPane.affine(
                1, 0, 0,
                0, -1.05, 0
            );
        }

        perspA11 = jSliderPerspA11.getValue();
    }//GEN-LAST:event_jSliderPerspA11StateChanged

    private void jSliderPerspA11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPerspA11MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPerspA11MouseReleased

    private void jSliderPerspA21StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPerspA21StateChanged
        if (jSliderPerspA21.getValue() > perspA21) {
            drawingPane.affine(
                1, 0, 0,
                0, 1, 0,
                0, 0.05, 1
            );
        } else {
            drawingPane.affine(
                1, 0, 0,
                0, 1, 0,
                0, -0.05, 1
            );
        }

        perspA21 = jSliderPerspA21.getValue();
    }//GEN-LAST:event_jSliderPerspA21StateChanged

    private void jSliderPerspA21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPerspA21MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPerspA21MouseReleased

    private void jSliderPerspA20StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPerspA20StateChanged
        if (jSliderPerspA20.getValue() > perspA20) {
            drawingPane.affine(
                1, 0, 0,
                0, 1, 0,
                0.05, 0, 1
            );
        } else {
            drawingPane.affine(
                1, 0, 0,
                0, 1, 0,
                -0.05, 0, 1
            );
        }

        perspA20 = jSliderPerspA20.getValue();
    }//GEN-LAST:event_jSliderPerspA20StateChanged

    private void jSliderPerspA20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPerspA20MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPerspA20MouseReleased

    private void jSliderPerspA22StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPerspA22StateChanged
        if (jSliderPerspA22.getValue() > perspA22) {
            drawingPane.affine(
                1, 0, 0,
                0, 1, 0,
                0, 0, 1.05
            );
        } else {
            drawingPane.affine(
                1, 0, 0,
                0, 1, 0,
                0, 0, -1.05
            );
        }

        perspA22 = jSliderPerspA22.getValue();
    }//GEN-LAST:event_jSliderPerspA22StateChanged

    private void jSliderPerspA22MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderPerspA22MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderPerspA22MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private computervision.chapter2.ex22.DrawingPane drawingPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelR00;
    private javax.swing.JLabel jLabelR01;
    private javax.swing.JLabel jLabelR02;
    private javax.swing.JLabel jLabelR03;
    private javax.swing.JLabel jLabelR10;
    private javax.swing.JLabel jLabelR11;
    private javax.swing.JLabel jLabelR12;
    private javax.swing.JLabel jLabelR13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAffine;
    private javax.swing.JPanel jPanelPerspective;
    private javax.swing.JPanel jPanelRigid;
    private javax.swing.JPanel jPanelSimilarity;
    private javax.swing.JPanel jPanelTranslation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSliderA00;
    private javax.swing.JSlider jSliderA01;
    private javax.swing.JSlider jSliderA02;
    private javax.swing.JSlider jSliderA10;
    private javax.swing.JSlider jSliderA11;
    private javax.swing.JSlider jSliderA12;
    private javax.swing.JSlider jSliderPerspA00;
    private javax.swing.JSlider jSliderPerspA01;
    private javax.swing.JSlider jSliderPerspA02;
    private javax.swing.JSlider jSliderPerspA10;
    private javax.swing.JSlider jSliderPerspA11;
    private javax.swing.JSlider jSliderPerspA12;
    private javax.swing.JSlider jSliderPerspA20;
    private javax.swing.JSlider jSliderPerspA21;
    private javax.swing.JSlider jSliderPerspA22;
    private javax.swing.JSlider jSliderSimA;
    private javax.swing.JSlider jSliderSimB;
    private javax.swing.JSlider jSliderSimTX;
    private javax.swing.JSlider jSliderSimTY;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }public void updateResultValues(double axR, double ayR, double bxR, double byR, double cxR, double cyR, double dxR, double dyR) {
        DecimalFormat df = new DecimalFormat("#.00");

        jLabelR00.setText(String.valueOf(df.format(axR)));
        jLabelR01.setText(String.valueOf(df.format(bxR)));
        jLabelR02.setText(String.valueOf(df.format(cxR)));
        jLabelR03.setText(String.valueOf(df.format(dxR)));
        jLabelR10.setText(String.valueOf(df.format(ayR)));
        jLabelR11.setText(String.valueOf(df.format(byR)));
        jLabelR12.setText(String.valueOf(df.format(cyR)));
        jLabelR13.setText(String.valueOf(df.format(dyR)));
        repaint();
    }
}
